app = "withered-frost-3196"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"
  CYPRESS_INSTALL_BINARY = "0"
  HUSKY_SKIP_INSTALL = "1"
  NODE_ENV = "production"
  FLY = "true"
  PRIMARY_REGION = "dfw"

[deploy]
  # TODO: remove migration one-off script
  release_command = "node ./other/runfile.js prisma-postgres/migrate.ts && npx prisma migrate deploy"

# IDEA: add back statics config here (fa0fbe9)

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 200
    soft_limit = 150
    type = "requests"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "20s"
    method = "get"
    path = "/healthcheck"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]
